-- medico PostgreSQL schema (mirror of schema.sql).
-- Used automatically when DATABASE_URL is postgresql:// or postgres://.

CREATE TABLE IF NOT EXISTS locations (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name      TEXT    NOT NULL,
    latitude  DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
    longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
    address   TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Synthetic patient assessments: no names or contact details are stored.
CREATE TABLE IF NOT EXISTS assessments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    patient_id  TEXT    NOT NULL,
    age_years   INTEGER NOT NULL,
    sex         TEXT    NOT NULL,
    urgency     TEXT    NOT NULL CHECK (urgency IN ('GREEN', 'ORANGE', 'RED')),
    decision    TEXT    NOT NULL,
    score       DOUBLE PRECISION NOT NULL,
    input_json  TEXT    NOT NULL,
    result_json TEXT    NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
